language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt

deploy:
  provider: pypi
  user: abn
  password:
    secure: i/xepORo+NMNI5w1VkeKiLlE+2Fm4ddoWqXmRD4KdU9KgCliprQpyV8q10fnYdJ7rQhGys2tO8inu4iHErFMt6+a7Mn3Sq1nTUHuX/1gVKCDxAqHvq8i6L/8yFx5MErBexjiz+P0pU4vGiA2xng4NP/vSNrlyUwaAVCHHJLnRX+5TvlKywvuw/NXPgoZ/+QmpJvOagmrHVmaA7nUszLv7KR794s12hZpWM0bFfbxvsj1KMz8Ne6CRVInPL1/2ethjus3dVJI4BWytnKWeZ5RwtQvsDl5AGl6TNlEDXTJAGo1cqidLIyW+1JXysEko2AY4ozzQld7wGOMiLWd/r+x350cfIh+VocqV9CDnShLav9/UiVh1eMcqzK4WMHE4xGjRIpnXlL+tx7pwP1ooZILB47320DRzr4MPkeD/X5qhQTyOjYSTgNkxFP+JB6r/5/XJZKo86+Al8/dCvDvrqiW/ExRp7+PxLY0KO7W4lkD1SCB0N2VZWWmi1AmvmyzzenvxQSHa7CpgLEJIaKYaIvNJwMlHWlzPbxUEuG2a1iUyVUoLHFJWIunVGhZNIkcpKbf32pgRodFyHYXFfFn7xrmFIqxFsA1fLD0J9nDiA6ROVIBNXpHjJd6kmUKo+8wDYAGb9DlWqcOlPvTIb/lOuP02fvWPIadnCeOo4U2dNfUFoU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: abn/python-cafe
