language: python
dist: xenial
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7

env:
  global:
    - secure: "BuYrI/qD0hvNGaPkLnHsBV9hJrhhlRGhDMyrEjRAWtdrLnG9WZLdnRdCAjgVPQRaH/zkTsOgoF0C2vOP2uk0qbpnC3omWTYmK0TYgJQvSzU4+6YsrsRkvsDxyPIZgUdo8eDQ23ZT1e/RnLTJHHM9hSmQCn9f2ef0Gm+OpPABz6SCYFNnLWxbmABFKRHe8PnJIGZbUjYgBd1dsEC3WXW17Qz2Ka3IeU3D2O15YoE3dx3aq/mAQJUkPCOE9FodOauxVqDkKrhmMMw4Mb9Iqi9+uBSDAln8udWMznnDurLuQ9BglVYF9Req/OVpfXbybwl04cPGC6ZmHEcaO/DjU1m3qz2JF3JD2G9Bi/l9RtSW1/NvUiPDtc4gZ2CHi4liAPg86n1u0DBgeENaaHzpzCn9fOD9FPjQLe/jFr18eTwxO7OpeCtgr6ROoVyEKDegZ17ejWVe4V9BZ5Eu0sQR75S1PrhZD9+INAFh+V7XFD7HJSlMQqjyiUCBPFTWOvoFY5Hx/2Zs7FMoyk5GhPZv4DCR/PLMDGdWvpF9Kt/jbESIVq4vcqLcKh4Qn+t262pvgwqK55IHqsn+7oflTHLQz3/gBlgH+KPYvjBNHB17sQzXa6Eq5LMgaXJ/NOxFOm+LP/qq9rhbM6zS7M804tQKnx0ABUx3eCOl8TKwgZOUAXE+zM4="

install:
  - pip install poetry
  - poetry add --dev appdirs
  - poetry install

script: ignore

jobs:
  include:
    - stage: build
      python: 3.6
      script:
        - poetry build
      if: tag IS NOT present
    - stage: deploy
      python: 3.6
      script:
        - poetry config http-basic.pypi "@token" "${PYPI_API_TOKEN}"
        - poetry publish --build
      if: tag IS present
