language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

env:
  global:
    - PYPI_USER=abn
    - secure: "IcWCXDQC3gml8KonFvf5jVXaOl254yph82YkLcOJvzuuI2z6qvQEvYBw6TA38Bu+UkXorJay/fw0hkPwbOc75FyjuKxirearhMavDUr1iLHIP158XbVOUAYTonD/t1qjq+eM6pe6If/tf6GmTM3HVNrdmZmLX3jkrHYtAdGlMpViXGWlB3AzQNdDhgAjU4hyTRRnzdA2KRqai/pwFi22ZdypF1zUJE5xQCa/jZJxOGZafDdrWsOYQmJ/QK0MPvsmGsgT7RvhAu+Urfme5lGP5AJsv1C6Aitf1AxFv4NkaFBNxDXfNuiLfJJpZjX0ypiv4RDSqq+0wcE07Ib4ddSEBvrNWMPeA/61KTolHOqSsGUvtU9iwDiQKgoYCmqWwIerzPGAMSVgultgWRkpXd7B/ZTQzfS1p95t0redtghm+kUUjcVtutJvNNQv8DMa/iaJk5Ol8YHTOiOzNeJ+e/NtKbLxycvcMZCnSpCLPcYIsP2K+UKqgEGpWEOVca7OUo4gXgkpg6FKaghwvePy6HAuDifMm60JYwMmHVtRLgnFSaATvSdfrNC6+zoRHs08v7orxfDQWy89YsuMDphUbH8lgC0GSSoEQv5GWQ+f5bAUIWdDmu/tLsqz2MlJmWjQ1f6saLrDRbRyt9ck2gZEq8vcdMgTcQQhXW4BOUGBByzGZJY="

install:
  - pip install poetry
  - poetry add --dev appdirs
  - poetry install

script: ignore

jobs:
  include:
    - stage: sonar
      python: 3.6
      addons:
        sonarcloud:
          organization: "abn-github"
          token:
            secure: "WX9mwPs3HVq4u6N9Nrlua4l3CxV+h9VGNZF3vR6SBZV6nJzQgfFKLvn8GjRktU1HgY3NvjOcs+nQrUmkH0FQeg544eCVhfxmUU/KkhCOEMD8Rpn6/kCXVZp8P2YIoRzehROPV45bB4TM+kw0u7bntM18CJFiC8gc30j/Ox27TVYBHtJh3mB+ueYjZGEckEFOZmR/r+IrC7otBApsghhRbp4+fg1f/1sWY2bhLx4rRa8sl5Le28Kuqu+Lh21Yj9UZvVsJFgP44lVm6olkG/7G23gEPlE/8FMkoTvaGUGfoAXwZgnbfLdwIuWjYxBgvM6MJMkbEJivRFiNSdjMf1ryyRiyHIE1Y703NtazMp/fm9oInv07Jrn3B2HUXQ4l8vUZjiJX4RiJ5tI3+lHTZRdkTrDdKDHT4fp3x7Q5PCdWOIrCjxtTAKUKijWCDNiftPZ6UWUACsXje9Uj+PD5UEK6Hnb7O9QYmaB4nWaFQ1hEchStCQer89Li/FSPxl/DkwQES8KcntKiQxgDEQn6NSEs0noBlwGhPb4B52fAoiQgLQV0X1ETaZR7Dr3tOrNS6IcLqw90OptmCTeXSqvaXGWytyTQyTPrshEsm3BvXJ6Co8sSYj+Yhi15QGxzeJf8JmuL3s0d+NyGeB5OlVy4kVrBPvInSzdaPsOyYXnbGN1MpO8="
          branches:
            - master
      script: sonar-scanner
    - stage: build
      python: 3.6
      script:
        - poetry build
      if: tag IS NOT present
    - stage: deploy
      python: 3.6
      script:
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
        - poetry publish --build
      if: tag IS present
